export const slides = [
  { id: 1, imgPath: "/client/a.webp" },
  { id: 2, imgPath: "/client/b.webp" },
  { id: 3, imgPath: "/client/c.webp" },
  { id: 4, imgPath: "/client/d.webp" },
  { id: 5, imgPath: "/client/e.webp" },
  { id: 6, imgPath: "/client/f.webp" },
  { id: 7, imgPath: "/client/g.webp" },
  { id: 8, imgPath: "/client/h.webp" },
  { id: 9, imgPath: "/client/i.webp" },
  { id: 10, imgPath: "/client/j.webp" },
  { id: 11, imgPath: "/client/k.webp" },
  { id: 12, imgPath: "/client/l.webp" },
  { id: 13, imgPath: "/client/m.webp" },
  { id: 14, imgPath: "/client/n.webp" },
  { id: 15, imgPath: "/client/o.webp" },
  { id: 16, imgPath: "/client/p.webp" },
  { id: 17, imgPath: "/client/q.jpeg" },
];
